### ISSUE TITLE
Error during character creation

### ISSUE THREAD

**Issue by kenny-evitt** [Dogeek/rpg-text#3]
My Python version:

```
$ python3 -V
Python 3.7.3
```

I ran `python3 main.py` from the root of the repo. I entered `New Game`.

Then:

```
Please enter your character's name.
> Bob
Please enter your desired job (thief, wizard, warrior, cleric).
> warrior
HP : 1 ; MP : 3 ; STR: 16 ; INT: 11 ; DEX: 9 ; CHR: 13 ; CON: 11 ; WIS: 12
Sum : 72
Are you satisfied with these stats?
Please enter 'yes', 'no', 'reroll', 'save', 'recall' or 'info'
> yes
> 
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    main()
  File "main.py", line 8, in main
    game.next_turn()
  File "/Users/kenny/@code/rpg-text/rpglib/game.py", line 34, in next_turn
    while not self.command_system.parse(command):
  File "/Users/kenny/@code/rpg-text/rpglib/command_system.py", line 53, in parse
    cmd, *cmd_args = command.split()
ValueError: not enough values to unpack (expected at least 1, got 0)
```

For the last prompt I just hit <kbd>Enter</kbd>.

**Comment by kenny-evitt** [comment]
Running `python3 main-gui.py` seemed to work to create a character (but then I couldn't figure out how to get past the character 'screen').

**Comment by sbordeyne** [comment]
The GUI is still in development, so no worries there.

For the console version, thanks it will be fixed tomorrow.
